// Generated by lungo 1.87.0 from Lean 4.34.1 for program tagged_urn_formal. Do not edit.
import * as L from "lungo-ts";

async function programModule() {
  const url = new URL("./program.wasm", import.meta.url);
  if (typeof process !== "undefined" && process.versions?.node) {
    const { readFile } = await import("node:fs/promises");
    return readFile(url);
  }
  const response = await fetch(url);
  if (!response.ok) throw new Error(`cannot load ${url}: ${response.status}`);
  return response.arrayBuffer();
}

/** Lean's TaggedUrn.Exec.Wf, held by handle: only the program's functions make and read its values. */
export class Wf extends L.Opaque {}

/** Describes TaggedUrn.Exec.Wf for polymorphic functions. */
export function wfType() {
  return new L.Type(
    L.inductiveExpr(0),
    (w, v) => {
      if (!(v instanceof Wf)) throw new L.MalformedError("not a TaggedUrn.Exec.Wf");
      L.OPAQUE.encode(w, v);
    },
    (r) => new Wf(r.program, r.u64()),
  );
}

/** Describes TaggedUrn.Constraint for polymorphic functions. */
export function constraintType() {
  return new L.Type(
    L.inductiveExpr(1),
    (w, v) => {
      if (typeof v !== "object" || v === null) throw new L.MalformedError("not a TaggedUrn.Constraint");
      switch (v.kind) {
        case "missing":
          w.u32(0);
          return;
        case "unconstrained":
          w.u32(1);
          return;
        case "optionalNot":
          w.u32(2);
          L.STRING.encode(w, v.value);
          return;
        case "present":
          w.u32(3);
          return;
        case "presentNot":
          w.u32(4);
          L.STRING.encode(w, v.value);
          return;
        case "exact":
          w.u32(5);
          L.STRING.encode(w, v.value);
          return;
        case "absent":
          w.u32(6);
          return;
        default:
          throw new L.MalformedError(`${String(v.kind)} is not a constructor of TaggedUrn.Constraint`);
      }
    },
    (r) => {
      const c = r.u32();
      switch (c) {
        case 0: return ({ kind: "missing" });
        case 1: return ({ kind: "unconstrained" });
        case 2: return ({ kind: "optionalNot", value: L.STRING.decode(r) });
        case 3: return ({ kind: "present" });
        case 4: return ({ kind: "presentNot", value: L.STRING.decode(r) });
        case 5: return ({ kind: "exact", value: L.STRING.decode(r) });
        case 6: return ({ kind: "absent" });
        default: throw new L.MalformedError(`constructor index ${c} of TaggedUrn.Constraint`);
      }
    },
  );
}

/** The layout fingerprint and descriptor of each type, by Lean name, for modules using them. */
export const leanTypes = Object.freeze({
  "TaggedUrn.Exec.Wf": Object.freeze({ fingerprint: "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785", type: wfType }),
  "TaggedUrn.Constraint": Object.freeze({ fingerprint: "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7", type: constraintType }),
});

/** The Lean program tagged_urn_formal. */
export class TaggedUrnFormal {
  #program;
  constructor(program) {
    this.#program = program;
  }
  comparable(a, b) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dcomparable", [], [[wfType(), a], [wfType(), b]], L.value(L.BOOL));
  }
  equivalent(a, b) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dequivalent", [], [[wfType(), a], [wfType(), b]], L.value(L.BOOL));
  }
  make(scheme, tags) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dmake", [], [[L.STRING, scheme], [L.list(L.pair(L.STRING, constraintType())), tags]], L.value(L.option(wfType())));
  }
  meets(a, b) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dmeets", [], [[wfType(), a], [wfType(), b]], L.value(L.BOOL));
  }
  meetsClosed(a, b) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dmeetsClosed", [], [[wfType(), a], [wfType(), b]], L.value(L.BOOL));
  }
  refines(a, b) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_drefines", [], [[wfType(), a], [wfType(), b]], L.value(L.BOOL));
  }
  refinesClosed(a, b) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_drefinesClosed", [], [[wfType(), a], [wfType(), b]], L.value(L.BOOL));
  }
  specificity(a) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dspecificity", [], [[wfType(), a]], L.value(L.NAT));
  }
  valuesMatch(inst, patt) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatch", [], [[constraintType(), inst], [constraintType(), patt]], L.value(L.BOOL));
  }
  valuesMatchClosed(inst, patt) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatchClosed", [], [[constraintType(), inst], [constraintType(), patt]], L.value(L.BOOL));
  }
  valuesMeet(a, b) {
    return this.#program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMeet", [], [[constraintType(), a], [constraintType(), b]], L.value(L.BOOL));
  }
}

/** Instantiates the program; `options.host` implements its externs. */
export async function load(options = {}) {
  const program = await L.Program.load(options.module ?? (await programModule()), { wasi: options.wasi });
  program.types("tagged_urn_formal__types");
  return new TaggedUrnFormal(program);
}
