// Generated by lungo 1.82.64 from Lean 4.34.1 for program tagged_urn_formal. Do not edit.
import * as L from "lungo-ts";

/** Lean's TaggedUrn.Exec.Wf, held by handle: only the program's functions make and read its values. */
export class Wf extends L.Opaque {
  private constructor();
}
export function wfType(): L.Type<Wf>;

/** Lean's TaggedUrn.Constraint. */
export type Constraint =
  | { readonly kind: "missing" }
  | { readonly kind: "unconstrained" }
  | { readonly kind: "optionalNot"; readonly value: string }
  | { readonly kind: "present" }
  | { readonly kind: "presentNot"; readonly value: string }
  | { readonly kind: "exact"; readonly value: string }
  | { readonly kind: "absent" }
;
export function constraintType(): L.Type<Constraint>;

/** The layout fingerprint and descriptor of each type, by Lean name, for modules using them. */
export const leanTypes: {
  readonly [lean: string]: { readonly fingerprint: string; readonly type: (...args: L.Type<any>[]) => L.Type<any> };
};

/** The Lean program tagged_urn_formal. */
export class TaggedUrnFormal {
  private constructor();
  /** Lean's TaggedUrn.Exec.comparable : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
  comparable(a: Wf, b: Wf): boolean;
  /** Lean's TaggedUrn.Exec.equivalent : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
  equivalent(a: Wf, b: Wf): boolean;
  /** Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf */
  make(scheme: string, tags: Array<[string, Constraint]>): L.Option<Wf>;
  /** Lean's TaggedUrn.Exec.meets : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
  meets(a: Wf, b: Wf): boolean;
  /** Lean's TaggedUrn.Exec.meetsClosed : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
  meetsClosed(a: Wf, b: Wf): boolean;
  /** Lean's TaggedUrn.Exec.refines : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
  refines(a: Wf, b: Wf): boolean;
  /** Lean's TaggedUrn.Exec.refinesClosed : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
  refinesClosed(a: Wf, b: Wf): boolean;
  /** Lean's TaggedUrn.Exec.specificity : TaggedUrn.Exec.Wf → Nat */
  specificity(a: Wf): bigint;
  /** Lean's TaggedUrn.Exec.valuesMatch : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool */
  valuesMatch(inst: Constraint, patt: Constraint): boolean;
  /** Lean's TaggedUrn.Exec.valuesMatchClosed : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool */
  valuesMatchClosed(inst: Constraint, patt: Constraint): boolean;
  /** Lean's TaggedUrn.Exec.valuesMeet : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool */
  valuesMeet(a: Constraint, b: Constraint): boolean;
}

export interface LoadOptions {
  /** The program module (default: `program.wasm` next to this file). */
  module?: WebAssembly.Module | BufferSource;
  wasi?: L.Wasi;
}

export function load(options?: LoadOptions): Promise<TaggedUrnFormal>;
